DROP TABLE SAGE_TEST.POSTS CASCADE CONSTRAINTS ;

DROP TABLE SAGE_TEST."USER" CASCADE CONSTRAINTS ;

CREATE TABLE SAGE_TEST.POSTS
  (
    POST_ID   NUMBER NOT NULL ,
    USER_ID   NUMBER NOT NULL ,
    POST_BODY VARCHAR2 (500)
  ) ;
ALTER TABLE SAGE_TEST.POSTS ADD CONSTRAINT POSTS_PK PRIMARY KEY ( POST_ID ) ;


CREATE TABLE SAGE_TEST."USER"
  (
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    USER_ID    NUMBER NOT NULL ,
    USERNAME   VARCHAR2 (20)
  ) ;
ALTER TABLE SAGE_TEST."USER" ADD CONSTRAINT USER_PK PRIMARY KEY ( USER_ID ) ;


ALTER TABLE SAGE_TEST.POSTS ADD CONSTRAINT POSTS_USER_FK FOREIGN KEY ( USER_ID ) REFERENCES SAGE_TEST."USER" ( USER_ID ) ;

CREATE SEQUENCE SAGE_TEST.POSTS_POST_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER SAGE_TEST.POSTS_POST_ID_TRG BEFORE
  INSERT ON SAGE_TEST.POSTS FOR EACH ROW WHEN (NEW.POST_ID IS NULL) BEGIN :NEW.POST_ID := SAGE_TEST.POSTS_POST_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE SAGE_TEST.USER_USER_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER SAGE_TEST.USER_USER_ID_TRG BEFORE
  INSERT ON SAGE_TEST."USER" FOR EACH ROW WHEN (NEW.USER_ID IS NULL) BEGIN :NEW.USER_ID := SAGE_TEST.USER_USER_ID_SEQ.NEXTVAL;
END;
/