DROP TABLE SAGE_TEST.POSTS CASCADE CONSTRAINTS ;

DROP TABLE SAGE_TEST.PROFILES CASCADE CONSTRAINTS ;

DROP TABLE SAGE_TEST.SEQUENCE_NO_TRIGGER CASCADE CONSTRAINTS ;

DROP TABLE SAGE_TEST.USERS CASCADE CONSTRAINTS ;

DROP SEQUENCE SAGE_TEST.USERS_USER_ID_SEQ;
DROP SEQUENCE SAGE_TEST.POSTS_POST_ID_SEQ;
DROP SEQUENCE SAGE_TEST.SEQUENCE_NO_TRIGGER_SEQUENCE_N;

CREATE TABLE SAGE_TEST.POSTS
  (
    POST_ID   NUMBER NOT NULL ,
    USER_ID   NUMBER NOT NULL ,
    POST_BODY VARCHAR2 (500)
  ) ;
ALTER TABLE SAGE_TEST.POSTS ADD CONSTRAINT POSTS_PK PRIMARY KEY ( POST_ID ) ;


CREATE TABLE SAGE_TEST.PROFILES
  (
    USER_ID NUMBER NOT NULL ,
    BIO     VARCHAR2 (500)
  ) ;


CREATE TABLE SAGE_TEST.SEQUENCE_NO_TRIGGER
  (
    SEQUENCE_NO_TRIGGER_ID NUMBER NOT NULL,
    VALUE VARCHAR2 (50)
  ) ;
ALTER TABLE SAGE_TEST.SEQUENCE_NO_TRIGGER ADD CONSTRAINT SEQUENCE_NO_TRIGGER_PK PRIMARY KEY ( SEQUENCE_NO_TRIGGER_ID ) ;


CREATE TABLE SAGE_TEST.USERS
  (
    USER_ID    NUMBER NOT NULL ,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    USERNAME   VARCHAR2 (20)
  ) ;
ALTER TABLE SAGE_TEST.USERS ADD CONSTRAINT USER_PK PRIMARY KEY ( USER_ID ) ;


ALTER TABLE SAGE_TEST.POSTS ADD CONSTRAINT POSTS_USER_FK FOREIGN KEY ( USER_ID ) REFERENCES SAGE_TEST.USERS ( USER_ID ) ;

ALTER TABLE SAGE_TEST.PROFILES ADD CONSTRAINT PROFILES_USERS_FK FOREIGN KEY ( USER_ID ) REFERENCES SAGE_TEST.USERS ( USER_ID ) ;

CREATE SEQUENCE SAGE_TEST.POSTS_POST_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER SAGE_TEST.POSTS_POST_ID_TRG BEFORE
  INSERT ON SAGE_TEST.POSTS FOR EACH ROW WHEN (NEW.POST_ID IS NULL) BEGIN :NEW.POST_ID := SAGE_TEST.POSTS_POST_ID_SEQ.NEXTVAL;
END;

CREATE SEQUENCE SAGE_TEST.SEQUENCE_NO_TRIGGER_SEQUENCE_N START WITH 1 NOCACHE ORDER ;

CREATE SEQUENCE SAGE_TEST.USERS_USER_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER SAGE_TEST.USERS_USER_ID_TRG BEFORE
  INSERT ON SAGE_TEST.USERS FOR EACH ROW WHEN (NEW.USER_ID IS NULL) BEGIN :NEW.USER_ID := SAGE_TEST.USERS_USER_ID_SEQ.NEXTVAL;
END;